server:
  shutdown: immediate
  port: 9091

notification:
  banner:
    roles: Local Role page message
    empty:
    dpsmenu: Local DPS menu page message


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/manage-users-db
    username: admin
    password: admin_password

application:
  # test key which doesn't send emails, but is automatically accepted by notify
  notify:
    key: testkey-992308b2-1e8f-4667-816b-8bdde781a4ac-9c211cf4-96d1-4c30-848b-8f172bca0b41

hmpps-auth:
  external:
    endpoint:
      url: http://localhost:9090/auth
  endpoint:
    url: http://localhost:9090/auth
  enabled: true
  client:
    client-id: hmpps-manage-users-api
    client-secret: clientsecret

nomis:
  endpoint:
    url: http://localhost:8082
    timeout: 1s
    extended-timeout: 3m
  client:
    client-id: manage-users-api-nomis-client
    client-secret: clientsecret

external-users:
  endpoint:
    url: http://localhost:8088
    timeout: 1s
  client:
    client-id: manage-users-api-ext-users-client
    client-secret: clientsecret

delius:
  endpoint:
    url: http://localhost:8099
    timeout: 1s
  client:
    client-id: manage-users-api-delius-client
    client-secret: clientsecret
  roles:
    mappings:
      TEST_ROLE:
        - 'ROLE_LICENCE_RO'
        - 'ROLE_GLOBAL_SEARCH'
      TEST_WORKLOAD_MEASUREMENT_ROLE:
        - 'ROLE_WORKLOAD_MEASUREMENT'
      TEST_MANAGE_A_WORKFORCE_ALLOCATE_ROLE:
        - 'ROLE_MANAGE_A_WORKFORCE_ALLOCATE'

hmpps:
  sqs:
    provider: localstack
    queues:
      bulkuserjobqueue:
        queueName: bulkUserJobQueue
        asyncQueueClient: true
        dlqName: bulkUserJobDlq
      bulkuserjobitemqueue:
        queueName: bulkUserJobItemQueue
        asyncQueueClient: true
        dlqName: bulkUserJobItemDlq